- name: Bootstrap a JUNOS network device
  hosts: qfx
  become: true
  gather_facts: true
  connection: local
  tasks:
    - name: Configure switch
      ansible.builtin.import_role:
        name: deployables.ocp.network