---
- name: Deploy VMs
  hosts: virtual_machines
  gather_facts: false
  become: false
  tasks:
    - name: Deploy VMs
      import_role:
        name: deployables.ocp.vms_deploy

    - name: Ensure all VMs are online
      ansible.builtin.wait_for_connection:
        timeout: 600
        sleep: 10
