---
ansible_user: ansible
cockpit_config:
  WebService:
    LoginTitle: "{{ inventory_hostname }}"
cockpit_packages:
  - cockpit
  - cockpit-bridge
  - cockpit-networkmanager
  - cockpit-machines
  - cockpit-packagekit
  - cockpit-podman
  - cockpit-selinux
  - cockpit-storaged
  - cockpit-system
  - cockpit-ws
kickstart_network_config:
  ip: 192.168.100.250
  gateway: 192.168.100.1
  netmask: 255.255.255.0
  nameserver: 192.168.100.1
network_connections:
  - name: bond0
    type: bond
    bond:
      mode: 802.3ad
      lacp_rate: fast
      miimon: 140
    cloned_mac: b4:45:06:f2:a4:91
    interface_name: bond0
    state: up
    ip:
      address:
        - 192.168.100.250/24
      gateway4: 192.168.100.1
      dns:
        - 192.168.100.1
      dns_search:
        - uotest01.poc.lab.local
        - poc.lab.local
      auto6: false
  - name: enp4s0
    type: ethernet
    interface_name: enp4s0
    port_type: bond
    controller: bond0
    state: up
  - name: enp5s0
    type: ethernet
    interface_name: enp5s0
    port_type: bond
    controller: bond0
    state: up
rhc_state: present
rhc_insights:
  state: absent
rhc_repositories:
  - name: rhel-9-for-x86_64-baseos-rpms
    state: enabled
  - name: rhel-9-for-x86_64-appstream-rpms
    state: enabled
podman_firewall:
  - port: 8444/tcp
    state: enabled
  - port: 2222/tcp
    state: enabled
podman_create_host_directories: true
podman_host_directories:
  "/home/ansible/gitlab/config":
    owner: root
    group: root
    mode: "0750"
  "/home/ansible/gitlab/logs":
    owner: root
    group: root
    mode: "0750"
  "/home/ansible/gitlab/data":
    owner: root
    group: root
    mode: "0750"
podman_kube_specs:
  - state: started
    run_as_user: root
    run_as_group: root
    kube_file_content: "{{ lookup('template', 'gitlab-pod.yaml') | from_yaml }}"